version: '3.8'
services:
  app:
    container_name: Warehouse_Service
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - 5001:5001
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - WAREHOUSE_GRPC_URL=${WAREHOUSE_GRPC_URL}